// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7aciVLC-VXwZq25MUUEo6hITOJn_ood0',
    appId: '1:734104480044:web:6a85cf466757bec80d2489',
    messagingSenderId: '734104480044',
    projectId: 'socialpreneur-hackathon',
    authDomain: 'socialpreneur-hackathon.firebaseapp.com',
    storageBucket: 'socialpreneur-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcfeKc5R4tgtyoVsccZwNpmZnGJ4Kmck',
    appId: '1:734104480044:android:4d66f2a6a5ac58750d2489',
    messagingSenderId: '734104480044',
    projectId: 'socialpreneur-hackathon',
    storageBucket: 'socialpreneur-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn9xNieTkPFKbvh638oun7_J4S08syh40',
    appId: '1:734104480044:ios:abcead7620def57f0d2489',
    messagingSenderId: '734104480044',
    projectId: 'socialpreneur-hackathon',
    storageBucket: 'socialpreneur-hackathon.appspot.com',
    iosBundleId: 'dev.manasmalla.socialpreneur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn9xNieTkPFKbvh638oun7_J4S08syh40',
    appId: '1:734104480044:ios:88c3271d596f88480d2489',
    messagingSenderId: '734104480044',
    projectId: 'socialpreneur-hackathon',
    storageBucket: 'socialpreneur-hackathon.appspot.com',
    iosBundleId: 'dev.manasmalla.socialpreneur.RunnerTests',
  );
}
